name: Continuous Release
on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
      - run: flutter pub get
      - name: Build for Android
      - run: flutter build apk --release
      - name: Build for Web
      - run: flutter build web --release

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android Release
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Web Release
          path: build/web/

      - name: Create Continuous Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'kattschan/openwrt_flutter' }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -fLOSs --retry 2 --retry-delay 60 https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh build/app/outputs/flutter-apk/app-release.apk
