name: Continuous Release
on:
  push:
    paths-ignore:
    - 'README.md'
  pull_request:
    paths-ignore:
    - 'README.md'
jobs:
  main:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build ipa --release --no-codesign
      - run: flutter build apk --release
      - run: flutter build web --release

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android Release
          path: build/app/outputs/flutter-apk/app.release.apk

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Web Release
          path: build/web/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows Release
          path: build/windows/x64/runner/Release/openwrt_flutter.exe
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS Release
          path: build/ios/ipa/*.ipa 

      - name: Upload Continuous Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'kattschan/openwrt_flutter' }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            curl -fLOSs --retry 2 --retry-delay 60 https://github.com/probonopd/uploadtool/raw/master/upload.sh
            bash upload.sh build/app/outputs/flutter-apk/app.release.apk build/windows/x64/runner/Release/openwrt_flutter.exe
